# Generated by Django 3.1 on 2021-07-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibackendapp', '0002_auto_20210710_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='rol',
        ),
    ]
