# Generated by Django 3.1 on 2021-07-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mibackendapp', '0005_auto_20210710_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
