# Generated by Django 3.1 on 2021-07-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mibackendapp', '0007_auto_20210710_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
