# Generated by Django 3.1 on 2021-07-11 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mibackendapp', '0008_auto_20210710_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='CarroCompras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalProduct', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('date_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.estado')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcion', models.CharField(max_length=200)),
                ('dimensiones', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.estado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.item')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.FileField(blank=True, max_length=250, null=True, upload_to='producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('imagen', models.FileField(blank=True, max_length=250, null=True, upload_to='items')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dateCreated', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costoEntrega', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(max_length=20)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.carrocompras')),
                ('metodoPago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=20)),
                ('dateUpdated', models.DateField()),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarroProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.carrocompras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='BodegaItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.item')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='AdminItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mibackendapp.item')),
            ],
        ),
    ]
